[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Configuración específica para SPA (Single Page Application)
[build]
  publish = "dist/app/browser"
  command = "npm run netlify-build"

# Headers para mejorar seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
